/**
 * 歌单Item
 */
export class RecommendPlaylistItemConstants {
  /**
   * 宽度
   */
  static readonly WIDTH: number = 250;
  /**
   * 高度
   */
  static readonly HEIGHT: number = 350;
  /**
   * image宽度
   */
  static readonly IMAGE_WIDTH: number = 250;
  /**
   * image高度
   */
  static readonly IMAGE_HEIGHT: number = 250;
  /**
   * 模糊度
   */
  static readonly BLUR: number = 100;
  /**
   * 圆角半径
   */
  static readonly BORDER_RADIUS: number = 15;
  /**
   * 字体颜色
   */
  static readonly FONT_COLOR: string = '#fff';
  /**
   * 最大行数
   */
  static readonly MAX_LINES: number = 2;
  /**
   * 最大字体大小
   */
  static readonly MAX_FONT_SIZE: number = 20;
  /**
   * 最小字体大小
   */
  static readonly MIN_FONT_SIZE: number = 18;
  /**
   * 边距
   */
  static readonly PADDING: number = 20;
}
