export class ComponentConstants {
  /**
   * 首页索引
   */
  static readonly HOME_INDEX: number = 0;
  /**
   * 收藏页索引
   */
  static readonly LOVE_INDEX: number = 1;
  /**
   * 导航按钮间距
   */
  static readonly NAVIGATION_BUTTON_SPACE: number = 5;
  /**
   * 导航按钮图标大小
   */
  static readonly NAVIGATION_BUTTON_ICON_SIZE: number = 25;
  /**
   * 导航按钮字体大小
   */
  static readonly NAVIGATION_BUTTON_TEXT_SIZE: number = 10;
  /**
   * 状态栏高度
   */
  static readonly STATUS_BAR_HEIGHT_KEY: string = 'statusBarHeight'
}


export class DataConstants{
  static readonly PREFERENCES_COOKIE_KEY: string = 'cookie';
}
